### ISSUE TITLE
Replace Uptime Robot with some kind of uptime/outage detector

### ISSUE THREAD

**Issue by rcheetham** [azavea/opendataphilly-jkan#115]
Azavea used Uptime Robot to determine whether OpenDataPhilly was available and alert if there was a problem. We need to separate this out from the rest of the Azavea/Element84 accounts. Should we simply create a new account with Uptime Robot or do something else?

**Comment by BryanQuigley** [comment]
I think the 3 cases for the site going down are:

- GitHub is down -nothing really to do.
- publish a bad site - unlikely, but would need a solution that checks content as well which makes it more complicated.  I'm thinking we don't try to do this and just check that it's up.
- misconfiguration - mostly set it and forget it.  Once we are on the new setup this should be pretty static.

I'm not sure we need an uptime checker given these - and plenty would work for free including Uptime Robot.

If we want to do a basic check and are ok doing one check per hour I've got a slight preference for the open source - but hosted for free at our rate [GlitchTip](https://glitchtip.com/documentation/uptime-monitoring).  Was looking at using them at Azavea but they didn't have the features we needed at the time but have since added some of them (features not relevant for ODP though).

**Comment by BryanQuigley** [comment]
GlitchTip actually has support for checking for specific words being on the page - which seems like a good check.

Setup a GlitchTip org and we can just signin with GitHub if I understand correctly.

**Comment by rcheetham** [comment]
I also have a preference for an open source solution. If you recommend GlitchTip, let's go with that.

**Comment by rcheetham** [comment]
@BryanQuigley set up a GlitchTip account and it is now monitoring the site. I have removed the entry from Uptime Robot.
