### ISSUE TITLE
Usability/design check for upstream JKAN

### ISSUE THREAD

**Issue by BryanQuigley** [azavea/opendataphilly-jkan#6]
If possible, let's do a quick pass to see what can be improved from a user perspective.  Time box and make new issues if bigger tasks. 

The goal would be to contribute to upstream, but to show lots of datasets this repo may be more useful sooner.

The upstream repo is currently at: https://github.com/timwis/jkan/tree/v2.

Notes: 
* part of the goal was to have most functionality work without javascript.
* we are not planning to use the editing bit (was Netlify CMS) for OpenDataPhilly 

hope to have a better test site up with data soon, but for now the most up-to-date site is https://bryanquigley.github.io/jkan/

But basically the current https://www.opendataphilly.org/ looks better.  Some functionality we are just going to lose moving from CKAN to JKAN (doing for less maintenance/cost going forward)

The goal of this ticket is to identify usability or other design improvements that don't require adding functionality.

**Comment by philippschmitt** [comment]
I took a look at the site today. Here's my notes. We can break them out into separate issues as needed.

## **A. General**
In response to this issue: https://github.com/timwis/jkan/issues/253
Since it’s already a bootstrap site, the proposed update to BS5 sounds like a good starting point before doing any other theming.

## **B. Homepage** / https://next.opendataphilly.org
1. Suggested feature: Add the ability to include a custom header image (See Bootstrap example “Responsive left-aligned hero with image“ on https://getbootstrap.com/docs/5.0/examples/heroes 
2. Suggested feature: Add a search box to the homepage to match old OpenDataPhilly site. On submit, forward to Datasets page and populate search there.
3. UX: Rename “Start browsing” to “Browse all datasets”
4. UI: Improve Category list:
  - Use a card component
  - clarify hover state (highlight card/icon, not just text underline)
  - Left align cards if they don't fill the entire row (use CSS Grid)

## **C. Datasets page** / https://next.opendataphilly.org/datasets
1. UI: Sidebar: Increase spacing between Categories and Organizations
2. UI: Sidebar: Change count pill for selected category and X button to white background
3. UI: Results: Increase spacing to make list more legible

## **D. Organizations page** / https://next.opendataphilly.org/organizations
1. Make layout responsive, e.g. 1-2 horizontal cards per org ([Bootstrap component](https://getbootstrap.com/docs/5.0/components/card/#horizontal))

## **E. Categories page** / https://next.opendataphilly.org/organizations
1. Use same card layout as Categories section on homepage

**Comment by BryanQuigley** [comment]
Thanks again!

Made new issues for the individual pieces off of https://github.com/azavea/opendataphilly-jkan/issues/11.  Feel free to revise if I got things wrong or if there is more context I lost.

**Comment by BryanQuigley** [comment]
Closing this design check.  Thank you for the suggestions!
