### ISSUE TITLE
Update README and/or Contributing to be for OpenDataPhilly and not JKAN (May require some thought going into how we keep docs/ up-to-date with JKAN if we want it customized too) - easy/medium

### ISSUE THREAD

**Issue by BryanQuigley** [azavea/opendataphilly-jkan#93]
There are multiple ways to do this, but at the very least the main README should make it clear that we are based on JKAN and how to contribute to OpenDataPhilly.

Open to other ideas, but it's likely better to not modify docs/ so we can keep them up-to-date with upstream changes.

**Comment by arigas2** [comment]
Here are my initial thoughts for README. I've pulled parts from the OpenDataPhilly proposal to CodeForPhilly and the JKAN README:


OpenDataPhilly](https://www.opendataphilly.org/) is a regional open data catalog, providing a repository for information about open data available from the City of Philadelphia, non-profit organizations, university research projects, and other publishers of open data about the region.

OpenDataPhilly was recently migrated from [CKAN](https://wwww.ckan.org/) to [JKAN](https://jkan.io/) by Azavea and Element 84, moving it from a database-driven application to a static web site.

**Motivations for Open Source Community**
While most open data catalogs are maintained by a single government entity, we believe that a diverse array of open data is more useful to the community than many repositories with discrete collections. We seek to maintain the regional character of OpenDataPhilly while growing the community of users and contributors to the catalog.

Azavea and Element 84 have provided support for OpenDataPhilly on a pro bono basis for more than a decade, but the acquisition of Azavea has highlighted the dependency on a single organization’s goodwill to sustain the project. In the long run, we seek to grow the community of contributors to the project in order to improve resilience and sustainability of the effort.

**What is JKAN? (link to that repo here)**
A lightweight, backend-free open data portal, powered by Jekyll
Open-source data portals can be really hard to install and maintain. But their basic purpose of providing links to download data really isn't that complicated. JKAN is a proof-of-concept that allows a small, resource-strapped government agency to stand-up an open data portal by simply [clicking the fork button](https://help.github.com/articles/fork-a-repo/).

**How to Contribute**
https://app.element.io/#/room/#opendataphilly:matrix.org (don’t know if this wants to be shared on GitHub)
Have a link to Issues (and highlight Good First Issues)
Running Locally (included on JKAN, but thought it would be helpful to include here)

**Comment by BryanQuigley** [comment]
Looks good to me! Thanks

Suggestions:
I think we can drop the bit about the migration
And Motivations for Open Source Community can be just one paragraph.
We can just link to the JKAN repo and the 1 line summary is fine.
Maybe split Running Locally to How to build - like how to contribute, definitely want to expand that section eventually.

**Comment by BryanQuigley** [comment]
FYI you can close the issue automatically as part of the git commit message: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
